require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '16.0'
prepare_react_native_project!

use_frameworks! :linkage => :static  

target 'CityPulse' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'Firebase/Auth'
  pod 'GoogleUtilities',         :modular_headers => true
  pod 'PromisesObjC',            :modular_headers => true
  pod 'FirebaseCoreInternal',    :modular_headers => true
  pod 'FirebaseCoreExtension',   :modular_headers => true
  pod 'FirebaseAuthInterop',     :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseFirestoreInternal', :modular_headers => true
  pod 'RecaptchaInterop',        :modular_headers => true
  pod 'nanopb',                  :modular_headers => true

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    patched_pods = %w[
      GoogleUtilities
      PromisesObjC
      FirebaseCoreInternal
      FirebaseCoreExtension
      FirebaseAuthInterop
      FirebaseFirestoreInternal
      FirebaseAppCheckInterop
      RecaptchaInterop
      nanopb
    ]

    installer.pods_project.targets.each do |target|
      if patched_pods.include?(target.name)
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        end
      end
    end
  end
end
